### ISSUE TITLE
Not working. Cant run script

### ISSUE THREAD

**Issue by lynrayy** [xtotdam/dynmap-assemble#5]
**Firstly i tried launch script double-clicking on it. It launches some kind of console window which closed immediately.

Then i opened Python 3.9 (exe) and tried drag-and-drop script on it. There is result:**

```
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> "C:\Users\LYN\Desktop\[MC]Сервер\Trim World 1.17.1\plugins\dynmap\web\tiles\dynmap-assemble.py"
  File "<stdin>", line 1
    "C:\Users\LYN\Desktop\[MC]Сервер\Trim World 1.17.1\plugins\dynmap\web\tiles\dynmap-assemble.py"
                                                                                                   ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
>>>


```

**Comment by xtotdam** [comment]
This is caused by the fact you are passing a string to python, not the command (more about it here https://docs.python.org/3/tutorial/interpreter.html)
Try `python dynmap-assemble.py` inside your terminal / cmd.exe window, not in Python REPL.
Maybe even `python dynmap-assemble.py -i` for the interactive mode.
